/// Flutter icons QR__Scannermath
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  QR__Scannermath
///      fonts:
///       - asset: fonts/QR__Scannermath.ttf
///
///
///
import 'package:flutter/widgets.dart';

class QR__Scannermath {
  QR__Scannermath._();

  static const _kFontFam = 'QR__Scannermath';

  static const IconData logo_2 = IconData(0xe800, fontFamily: _kFontFam);
}
